version: '3.8'

services:

  worker:
    build: .
    container_name: credito-analise-worker
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: search-credit-kafka:9092
    networks:
      - search-credit-network
    restart: unless-stopped

networks:
  search-credit-network:
    external: true
