services:
  credito-analise-worker:
    build: .
    container_name: credito-analise-worker
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: search-credit-kafka:9092
    networks:
      - search-credit-network
    restart: unless-stopped

networks:
  search-credit-network:
    external: true
